const GET_COURSES = 'GET_COURSES';

const ADD_COURSE = 'ADD_COURSE';

const DELETE_COURSE = 'DELETE_COURSE';

const UPDATE_COURSE = 'UPDATE_COURSE';

export {GET_COURSES, ADD_COURSE, DELETE_COURSE, UPDATE_COURSE};